from __future__ import annotations

from sc_core.execution import TaskResultHandle

from src.app.domain.tasks import TaskDetail, TaskProgress, TaskResultRefs
from src.app.infrastructure.catalog_seed_data import (
    FLOATING_QUBIT_WITH_XY_LINE_DEFINITION_ID,
    FLUXONIUM_READOUT_CHAIN_DEFINITION_ID,
    LOCAL_SPACE_RESONATOR_DEFINITION_ID,
)
from src.app.infrastructure.storage_reference_factory import (
    build_metadata_record_ref,
    build_result_handle_ref,
    build_result_provenance_ref,
    build_trace_payload_ref,
)


def build_seed_tasks() -> tuple[TaskDetail, ...]:
    return (
        TaskDetail(
            task_id=300,
            kind="simulation",
            lane="simulation",
            execution_mode="run",
            status="running",
            submitted_at="2026-03-17 08:45:00",
            owner_user_id="local-operator",
            owner_display_name="Local Operator",
            workspace_id="local-space",
            workspace_slug="local-space",
            visibility_scope="local",
            dataset_id="local-dataset-001",
            definition_id=LOCAL_SPACE_RESONATOR_DEFINITION_ID,
            summary="Local Space preview simulation is running.",
            queue_backend="rq_redis",
            worker_task_name="simulation_run_task",
            request_ready=True,
            submitted_from_active_dataset=True,
            progress=TaskProgress(
                phase="running",
                percent_complete=42,
                summary="simulation_run_task started in the local simulation lane.",
                updated_at="2026-03-17 08:50:00",
            ),
            result_refs=_empty_result_refs(),
        ),
        TaskDetail(
            task_id=301,
            kind="simulation",
            lane="simulation",
            execution_mode="run",
            status="running",
            submitted_at="2026-03-12 09:15:00",
            owner_user_id="researcher-01",
            owner_display_name="Rewrite Local User",
            workspace_id="ws-device-lab",
            workspace_slug="device-lab",
            visibility_scope="workspace",
            dataset_id="fluxonium-2025-031",
            definition_id=FLOATING_QUBIT_WITH_XY_LINE_DEFINITION_ID,
            summary="Fluxonium parameter sweep is running.",
            queue_backend="rq_redis",
            worker_task_name="simulation_run_task",
            request_ready=True,
            submitted_from_active_dataset=True,
            progress=TaskProgress(
                phase="running",
                percent_complete=55,
                summary="simulation_run_task started in the simulation lane.",
                updated_at="2026-03-12 09:22:00",
            ),
            result_refs=_empty_result_refs(),
        ),
        TaskDetail(
            task_id=302,
            kind="characterization",
            lane="characterization",
            execution_mode="run",
            status="queued",
            submitted_at="2026-03-12 08:40:00",
            owner_user_id="researcher-01",
            owner_display_name="Rewrite Local User",
            workspace_id="ws-device-lab",
            workspace_slug="device-lab",
            visibility_scope="workspace",
            dataset_id="transmon-coupler-014",
            definition_id=None,
            summary="Coupler dataset characterization is queued.",
            queue_backend="rq_redis",
            worker_task_name="characterization_run_task",
            request_ready=True,
            submitted_from_active_dataset=False,
            progress=TaskProgress(
                phase="queued",
                percent_complete=0,
                summary="Task accepted by the local runtime.",
                updated_at="2026-03-12 08:40:00",
            ),
            result_refs=_empty_result_refs(),
        ),
        TaskDetail(
            task_id=303,
            kind="post_processing",
            lane="simulation",
            execution_mode="run",
            status="completed",
            submitted_at="2026-03-11 19:05:00",
            owner_user_id="researcher-01",
            owner_display_name="Rewrite Local User",
            workspace_id="ws-device-lab",
            workspace_slug="device-lab",
            visibility_scope="owned",
            dataset_id="fluxonium-2025-031",
            definition_id=None,
            summary="Fluxonium fit bundle was post-processed.",
            queue_backend="rq_redis",
            worker_task_name="post_processing_run_task",
            request_ready=True,
            submitted_from_active_dataset=True,
            progress=TaskProgress(
                phase="completed",
                percent_complete=100,
                summary="post_processing_run_task completed in the simulation lane.",
                updated_at="2026-03-11 19:18:00",
            ),
            result_refs=_fluxonium_completed_result_refs(),
        ),
        TaskDetail(
            task_id=304,
            kind="simulation",
            lane="simulation",
            execution_mode="probe",
            status="queued",
            submitted_at="2026-03-11 17:40:00",
            owner_user_id="researcher-02",
            owner_display_name="Modeling User",
            workspace_id="ws-device-lab",
            workspace_slug="device-lab",
            visibility_scope="owned",
            dataset_id="fluxonium-2025-031",
            definition_id=FLUXONIUM_READOUT_CHAIN_DEFINITION_ID,
            summary="Private simulation draft remains owner-only.",
            queue_backend="rq_redis",
            worker_task_name="simulation_probe_task",
            request_ready=False,
            submitted_from_active_dataset=False,
            progress=TaskProgress(
                phase="queued",
                percent_complete=0,
                summary="Task accepted by the local runtime.",
                updated_at="2026-03-11 17:40:00",
            ),
            result_refs=_empty_result_refs(),
        ),
        TaskDetail(
            task_id=305,
            kind="characterization",
            lane="characterization",
            execution_mode="run",
            status="running",
            submitted_at="2026-03-11 16:55:00",
            owner_user_id="researcher-03",
            owner_display_name="Shared Workspace User",
            workspace_id="ws-modeling",
            workspace_slug="modeling",
            visibility_scope="workspace",
            dataset_id="transmon-coupler-014",
            definition_id=None,
            summary="Modeling workspace characterization is running.",
            queue_backend="rq_redis",
            worker_task_name="characterization_run_task",
            request_ready=True,
            submitted_from_active_dataset=False,
            progress=TaskProgress(
                phase="running",
                percent_complete=35,
                summary="characterization_run_task started in the characterization lane.",
                updated_at="2026-03-11 17:00:00",
            ),
            result_refs=_characterization_result_refs(),
        ),
    )


def _empty_result_refs() -> TaskResultRefs:
    return TaskResultRefs(
        result_handle=TaskResultHandle(),
        metadata_records=(),
        trace_payload=None,
        result_handles=(),
    )


def _fluxonium_completed_result_refs() -> TaskResultRefs:
    trace_batch_record = build_metadata_record_ref("trace_batch", "trace_batch:88", version=1)
    return TaskResultRefs(
        result_handle=TaskResultHandle(trace_batch_id=88),
        metadata_records=(
            trace_batch_record,
            build_metadata_record_ref("result_handle", "result_handle:501", version=2),
        ),
        trace_payload=build_trace_payload_ref(
            payload_role="task_output",
            store_key="datasets/fluxonium-2025-031/trace-batches/88.zarr",
            store_uri="trace_store/datasets/fluxonium-2025-031/trace-batches/88.zarr",
            group_path="trace_batches/88",
            array_path="signals/iq_real",
            dtype="float64",
            shape=(184, 1024),
            chunk_shape=(16, 1024),
        ),
        result_handles=(
            build_result_handle_ref(
                handle_id="result:fluxonium-2025-031:fit-summary",
                kind="fit_summary",
                status="materialized",
                label="Fluxonium fit summary",
                metadata_record=build_metadata_record_ref(
                    "result_handle",
                    "result_handle:501",
                    version=2,
                ),
                payload_backend="json_artifact",
                payload_format="json",
                payload_role="report_artifact",
                payload_locator="artifacts/fit-summary.json",
                provenance_task_id=303,
                provenance=build_result_provenance_ref(
                    source_dataset_id="fluxonium-2025-031",
                    source_task_id=303,
                    trace_batch_record=trace_batch_record,
                ),
            ),
            build_result_handle_ref(
                handle_id="result:fluxonium-2025-031:plot-bundle",
                kind="plot_bundle",
                status="materialized",
                label="Fluxonium plot bundle",
                metadata_record=build_metadata_record_ref(
                    "result_handle",
                    "result_handle:502",
                    version=1,
                ),
                payload_backend="bundle_archive",
                payload_format="zip",
                payload_role="bundle_artifact",
                payload_locator="artifacts/plot-bundle.zip",
                provenance_task_id=303,
                provenance=build_result_provenance_ref(
                    source_dataset_id="fluxonium-2025-031",
                    source_task_id=303,
                    trace_batch_record=trace_batch_record,
                ),
            ),
        ),
    )


def _characterization_result_refs() -> TaskResultRefs:
    analysis_run_record = build_metadata_record_ref("analysis_run", "analysis_run:12", version=4)
    return TaskResultRefs(
        result_handle=TaskResultHandle(analysis_run_id=12),
        metadata_records=(
            analysis_run_record,
            build_metadata_record_ref("result_handle", "result_handle:612", version=3),
        ),
        trace_payload=build_trace_payload_ref(
            payload_role="analysis_projection",
            store_key="datasets/transmon-coupler-014/analysis-runs/12.zarr",
            store_uri="trace_store/datasets/transmon-coupler-014/analysis-runs/12.zarr",
            group_path="analysis_runs/12",
            array_path="derived/chi_fit",
            dtype="float64",
            shape=(76, 64),
            chunk_shape=(16, 64),
        ),
        result_handles=(
            build_result_handle_ref(
                handle_id="result:transmon-coupler-014:characterization-report",
                kind="characterization_report",
                status="materialized",
                label="Coupler characterization report",
                metadata_record=build_metadata_record_ref(
                    "result_handle",
                    "result_handle:612",
                    version=3,
                ),
                payload_backend="markdown_artifact",
                payload_format="markdown",
                payload_role="report_artifact",
                payload_locator="artifacts/fit-report.md",
                provenance_task_id=305,
                provenance=build_result_provenance_ref(
                    source_dataset_id="transmon-coupler-014",
                    source_task_id=305,
                    analysis_run_record=analysis_run_record,
                ),
            ),
        ),
    )
