### A Pluto.jl notebook ###
# v1.0.1

#> [frontmatter]
#> title = "02 Readout Line Purcell Filter Point-Coupled"
#> tags = ["julia-core", "purcell-filter", "point-coupling", "half-wave-resonator"]
#> description = "Self-contained Julia Core Pluto tutorial for a point-capacitively coupled half-wave Purcell filter with real HBSolveResult plots."

using Markdown
using InteractiveUtils

# ╔═╡ 3f8d8209-58cb-45f8-946f-1f7df3460201
begin
    import Pkg

    core_project = normpath(joinpath(@__DIR__, "..", "..", "core", "julia", "SuperconductingCircuitsCore"))
    visualizer_project = normpath(joinpath(@__DIR__, "..", "..", "core", "julia", "SuperconductingCircuitsVisualizer"))
    core_project_file = normpath(joinpath(core_project, "Project.toml"))
    visualizer_project_file = normpath(joinpath(visualizer_project, "Project.toml"))
    active_project_file = normpath(something(Base.active_project(), ""))

    if active_project_file != core_project_file && active_project_file != visualizer_project_file
        Pkg.develop(path=core_project)
        Pkg.develop(path=visualizer_project)
    else
        core_project in LOAD_PATH || pushfirst!(LOAD_PATH, core_project)
        visualizer_project in LOAD_PATH || pushfirst!(LOAD_PATH, visualizer_project)
    end

    using SuperconductingCircuitsCore
    using SuperconductingCircuitsVisualizer

    figure_config = PlotlyFigureConfig(
        download_filename=splitext(basename(@__FILE__))[1],
    )

    include(joinpath(@__DIR__, "includes", "hb_example_helpers.jl"))
    using .HBExampleHelpers: db20, phase_deg, zero_mode_s, zero_mode_z
end

# ╔═╡ e1846358-72e8-4035-b841-e91a9c8b0202
md"""
# 02 Readout Line + Purcell Filter Point-Coupled

System:

```text
CPW readout input
    -> point capacitive coupling
    -> half-wave Purcell filter ladder
    -> point capacitive coupling
    -> CPW readout output
```

This notebook intentionally uses point capacitive coupling. It does not claim to model a finite distributed CPW / MTL coupling window.
"""

# ╔═╡ 17e4f6a0-e531-471d-aa52-ec336e617203
md"""
## Physics And Modeling Convention

A half-wave resonator has two voltage antinodes in the common open-open model. In this point-coupled model, both endpoints are open ladder nodes and each endpoint is coupled to the readout path through one lumped capacitor.

Point coupling is acceptable here as a first model because the coupling objects are treated as small localized capacitors, not as long parallel CPW sections. For distributed readout-line/QWR coupling, see Notebook 04.
"""

# ╔═╡ a9fb0e7b-cf4b-40cb-84dd-882bfb39d203
begin
    resonator_length_m = 4.0e-3
    section_length_m = 0.5e-3
    l_per_m_h = 4.2e-7
    c_per_m_f = 1.7e-10

    input_coupling_f = 2.0e-15
    output_coupling_f = 2.0e-15
    port_resistance = 50.0

    start_frequency = 2.0e9
    stop_frequency = 10.0e9
    point_count = 81

    pump_frequency = 12.0e9
    pump_current = 0.0

    optional_hb_kwargs = Dict{Symbol,Any}(
        :nbatches => 1,
        :iterations => 120,
        :ftol => 1e-8,
    )
end

# ╔═╡ 652eeafa-5efd-45ad-b815-d10589de0203
(
    half_wave_boundary="open-open ladder, capacitively coupled at both endpoints",
    input_coupling_f=input_coupling_f,
    output_coupling_f=output_coupling_f,
    section_count=TransmissionLineSpec(
        length_m=resonator_length_m,
        section_length_m=section_length_m,
        l_per_m_h=l_per_m_h,
        c_per_m_f=c_per_m_f,
    ).n_sections,
)

# ╔═╡ 8f379b09-74bf-4ec5-861e-9940a74b0204
md"""
## Julia Core Authoring

The half-wave ladder is generated by Core. The two endpoint couplings are explicit `couple_capacitive!` point relations inside the builder.
"""

# ╔═╡ 9f705655-942b-49e7-bd90-c1ec9db6f205
example = build_purcell_filter_mvp_example(
    resonator_length_m=resonator_length_m,
    section_length_m=section_length_m,
    l_per_m_h=l_per_m_h,
    c_per_m_f=c_per_m_f,
    input_coupling_f=input_coupling_f,
    output_coupling_f=output_coupling_f,
    port_resistance=port_resistance,
    start_frequency=start_frequency,
    stop_frequency=stop_frequency,
    point_count=point_count,
    pump_frequency=pump_frequency,
    pump_current=pump_current,
    optional_hb_kwargs=optional_hb_kwargs,
)

# ╔═╡ 7d509d58-68b6-433f-b891-12f7812b6206
(
    filter_head_termination=example.filter.head_termination,
    filter_tail_termination=example.filter.tail_termination,
    filter_nodes=length(example.filter.nodes),
    point_couplings=count(relation -> relation.role == :point_capacitive_coupling, example.graph.relations),
)

# ╔═╡ f1e24b37-af24-48de-908f-d0bbdba58a40
md"""
## EngineeringGraph And Compiled Netlist
"""

# ╔═╡ c79eba90-31d8-4980-9db3-92016818f207
example.graph.relations

# ╔═╡ b8d8abf5-a42d-4fcb-b043-664ddff413ab
example.compiled.netlist

# ╔═╡ 35cce815-a2c0-4694-ad30-2f254c3ac206
md"""
## HBProblemSpec And Real Solver Output
"""

# ╔═╡ 56f9419a-3081-4415-a2d2-1ef31f1e5e10
hb_problem = example.hb_problem

# ╔═╡ aa08e7a2-f15e-4df2-8651-2367c9c17074
result = run_hb_problem(hb_problem)

# ╔═╡ 32840fce-f8ac-4fdf-a2b2-d1cf8c49a205
begin
    frequencies_ghz = result.frequencies_hz ./ 1e9
    s11 = zero_mode_s(result, 1, 1)
    s21 = zero_mode_s(result, 2, 1)
    z11 = zero_mode_z(result, 1, 1)
    z21 = zero_mode_z(result, 2, 1)
end

# ╔═╡ 187d7f35-1985-44e2-9261-b0e602148206
(
    min_s21_db=minimum(db20(s21)),
    max_s11_db=maximum(db20(s11)),
    s21_feature_frequency_ghz=frequencies_ghz[argmin(db20(s21))],
)

# ╔═╡ e77ff0a6-6943-48fb-99a8-a49fb4f58207
s_parameter_magnitude_figure(
    result.frequencies_hz,
    ["S21" => s21];
    title="Point-Coupled Purcell Filter Transmission",
    config=figure_config,
)

# ╔═╡ 6d805a44-e846-4839-8e96-70c1a0307d07
s_parameter_magnitude_figure(
    result.frequencies_hz,
    ["S11" => s11];
    title="Point-Coupled Purcell Filter Reflection",
    config=figure_config,
)

# ╔═╡ 0f4eaa7f-1b67-4873-9db2-71b788207e1b
z_trace_figure(
    result.frequencies_hz,
    [
        "Z11" => z11,
        "Z21" => z21,
    ];
    title="Purcell Filter Z Parameters",
    config=figure_config,
)

# ╔═╡ Cell order:
# ╠═3f8d8209-58cb-45f8-946f-1f7df3460201
# ╟─e1846358-72e8-4035-b841-e91a9c8b0202
# ╟─17e4f6a0-e531-471d-aa52-ec336e617203
# ╠═a9fb0e7b-cf4b-40cb-84dd-882bfb39d203
# ╠═652eeafa-5efd-45ad-b815-d10589de0203
# ╟─8f379b09-74bf-4ec5-861e-9940a74b0204
# ╠═9f705655-942b-49e7-bd90-c1ec9db6f205
# ╠═7d509d58-68b6-433f-b891-12f7812b6206
# ╟─f1e24b37-af24-48de-908f-d0bbdba58a40
# ╠═c79eba90-31d8-4980-9db3-92016818f207
# ╠═b8d8abf5-a42d-4fcb-b043-664ddff413ab
# ╟─35cce815-a2c0-4694-ad30-2f254c3ac206
# ╠═56f9419a-3081-4415-a2d2-1ef31f1e5e10
# ╠═aa08e7a2-f15e-4df2-8651-2367c9c17074
# ╠═32840fce-f8ac-4fdf-a2b2-d1cf8c49a205
# ╠═187d7f35-1985-44e2-9261-b0e602148206
# ╠═e77ff0a6-6943-48fb-99a8-a49fb4f58207
# ╠═6d805a44-e846-4839-8e96-70c1a0307d07
# ╠═0f4eaa7f-1b67-4873-9db2-71b788207e1b
