### A Pluto.jl notebook ###
# v1.0.1

#> [frontmatter]
#> title = "03 Long Readout Line Baseline"
#> tags = ["julia-core", "readout-line", "cpw", "baseline"]
#> description = "Self-contained Julia Core Pluto tutorial for a long CPW readout-line baseline before adding a hanging QWR."

using Markdown
using InteractiveUtils

# ╔═╡ 0f70281a-4277-483c-95d8-8a49795b1101
begin
    import Pkg

    core_project = normpath(joinpath(@__DIR__, "..", "..", "core", "julia", "SuperconductingCircuitsCore"))
    visualizer_project = normpath(joinpath(@__DIR__, "..", "..", "core", "julia", "SuperconductingCircuitsVisualizer"))
    core_project_file = normpath(joinpath(core_project, "Project.toml"))
    visualizer_project_file = normpath(joinpath(visualizer_project, "Project.toml"))
    active_project_file = normpath(something(Base.active_project(), ""))

    if active_project_file != core_project_file && active_project_file != visualizer_project_file
        Pkg.develop(path=core_project)
        Pkg.develop(path=visualizer_project)
    else
        core_project in LOAD_PATH || pushfirst!(LOAD_PATH, core_project)
        visualizer_project in LOAD_PATH || pushfirst!(LOAD_PATH, visualizer_project)
    end

    using SuperconductingCircuitsCore
    using SuperconductingCircuitsVisualizer

    figure_config = PlotlyFigureConfig(
        download_filename=splitext(basename(@__FILE__))[1],
    )

    include(joinpath(@__DIR__, "includes", "hb_example_helpers.jl"))
    using .HBExampleHelpers: db20, phase_deg, zero_mode_s, zero_mode_z
end

# ╔═╡ 34b4ea7a-9824-44ca-9132-2bce25591102
md"""
# 03 Long Readout Line Baseline

This notebook is the baseline CPW readout line. It intentionally has no Purcell filter, no resonator, and no coupling window.

The baseline is useful before Notebook 04 adds a hanging quarter-wave resonator with a finite MTL coupling window.
"""

# ╔═╡ a95ae90a-b1d9-4d17-9834-18e4af7b1103
md"""
## Physics And Modeling Convention

A longer through line accumulates phase delay:

```text
phase delay roughly follows beta * length
```

Mismatch comes from the finite LC ladder approximation and the 50 ohm source/load terminations. The line still uses the same head/tail convention introduced in Notebook 01.
"""

# ╔═╡ c2dcf9e6-d47d-4a19-98f0-41b54c1e1104
begin
    line_length_m = 8.0e-3
    section_length_m = 0.5e-3
    l_per_m_h = 4.2e-7
    c_per_m_f = 1.7e-10
    port_resistance = 50.0

    start_frequency = 2.0e9
    stop_frequency = 10.0e9
    point_count = 81

    pump_frequency = 12.0e9
    pump_current = 0.0

    optional_hb_kwargs = Dict{Symbol,Any}(
        :nbatches => 1,
        :iterations => 120,
        :ftol => 1e-8,
    )
end

# ╔═╡ e659cf15-b06a-4702-88cc-89ae0d521105
(
    line_length_m=line_length_m,
    section_length_m=section_length_m,
    section_count=TransmissionLineSpec(
        length_m=line_length_m,
        section_length_m=section_length_m,
        l_per_m_h=l_per_m_h,
        c_per_m_f=c_per_m_f,
    ).n_sections,
    phase_velocity_m_per_s=phase_velocity(
        TransmissionLineSpec(
            length_m=line_length_m,
            section_length_m=section_length_m,
            l_per_m_h=l_per_m_h,
            c_per_m_f=c_per_m_f,
        ),
    ),
)

# ╔═╡ 4779c88d-9154-471f-8796-2dcc98a11106
md"""
## Julia Core Authoring

The readout line is generated by `build_lc_ladder_line!` inside the Core example builder. The returned `TransmissionLineLadder` exposes ordered nodes and section relations for inspection.
"""

# ╔═╡ 933de476-3e94-4d94-9dc6-e972cdd41107
example = build_long_readout_line_example(
    length_m=line_length_m,
    section_length_m=section_length_m,
    l_per_m_h=l_per_m_h,
    c_per_m_f=c_per_m_f,
    port_resistance=port_resistance,
    start_frequency=start_frequency,
    stop_frequency=stop_frequency,
    point_count=point_count,
    pump_frequency=pump_frequency,
    pump_current=pump_current,
    optional_hb_kwargs=optional_hb_kwargs,
)

# ╔═╡ 470e43ff-3d64-4542-84fe-5b6467511108
(
    head=example.line.head,
    tail=example.line.tail,
    section_count=length(example.line.series_inductors),
    node_count=length(example.line.nodes),
)

# ╔═╡ 5bbd21d0-bd9a-41b4-9fbb-e5c9fcd11109
md"""
## EngineeringGraph, Compiled Netlist, And HBProblemSpec
"""

# ╔═╡ 62da3146-29e5-4fb8-9ce8-24e70bf01110
filter(relation -> relation.relation_type == :transmission_line_ladder, example.graph.relations)

# ╔═╡ 1bd39615-cfea-4a27-aae8-d29ed8701111
example.compiled.netlist

# ╔═╡ 32990a3f-7bde-4d1d-aacf-a0c05e0e1112
hb_problem = example.hb_problem

# ╔═╡ d8a69d56-71d9-4a47-a181-0e2b14811113
result = run_hb_problem(hb_problem)

# ╔═╡ ec9bb960-5524-4120-8606-075733c31114
begin
    frequencies_ghz = result.frequencies_hz ./ 1e9
    s11 = zero_mode_s(result, 1, 1)
    s21 = zero_mode_s(result, 2, 1)
    z11 = zero_mode_z(result, 1, 1)
    z21 = zero_mode_z(result, 2, 1)
end

# ╔═╡ dff2b863-9a80-4c92-99bc-b62ef67b1115
(
    phase_delay_deg=phase_deg(s21)[end] - phase_deg(s21)[1],
    worst_reflection_db=maximum(db20(s11)),
    z21_samples=length(z21),
)

# ╔═╡ 9f2d1d6a-1a97-49bd-9a5d-f44517311116
s_parameter_phase_figure(
    result.frequencies_hz,
    ["S21" => s21];
    title="Long Readout Line Phase Delay",
    config=figure_config,
)

# ╔═╡ b23f05e7-4b0f-4e4e-9241-f3b87f971117
s_parameter_magnitude_figure(
    result.frequencies_hz,
    [
        "S21" => s21,
        "S11" => s11,
    ];
    title="Long Readout Line Transmission And Mismatch",
    config=figure_config,
)

# ╔═╡ fa2da5e9-7e26-44b1-992d-6318dd171118
z_trace_figure(
    result.frequencies_hz,
    [
        "Z11" => z11,
        "Z21" => z21,
    ];
    title="Long Readout Line Z Behavior",
    config=figure_config,
)

# ╔═╡ Cell order:
# ╠═0f70281a-4277-483c-95d8-8a49795b1101
# ╟─34b4ea7a-9824-44ca-9132-2bce25591102
# ╟─a95ae90a-b1d9-4d17-9834-18e4af7b1103
# ╠═c2dcf9e6-d47d-4a19-98f0-41b54c1e1104
# ╠═e659cf15-b06a-4702-88cc-89ae0d521105
# ╟─4779c88d-9154-471f-8796-2dcc98a11106
# ╠═933de476-3e94-4d94-9dc6-e972cdd41107
# ╠═470e43ff-3d64-4542-84fe-5b6467511108
# ╟─5bbd21d0-bd9a-41b4-9fbb-e5c9fcd11109
# ╠═62da3146-29e5-4fb8-9ce8-24e70bf01110
# ╠═1bd39615-cfea-4a27-aae8-d29ed8701111
# ╠═32990a3f-7bde-4d1d-aacf-a0c05e0e1112
# ╠═d8a69d56-71d9-4a47-a181-0e2b14811113
# ╠═ec9bb960-5524-4120-8606-075733c31114
# ╠═dff2b863-9a80-4c92-99bc-b62ef67b1115
# ╠═9f2d1d6a-1a97-49bd-9a5d-f44517311116
# ╠═b23f05e7-4b0f-4e4e-9241-f3b87f971117
# ╠═fa2da5e9-7e26-44b1-992d-6318dd171118
